2014-12-02 15:23:37,566 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.grails.test.spock.GrailsSpecTestType.doRun(GrailsSpecTestType.groovy:147)
	at org.codehaus.groovy.grails.test.support.GrailsTestTypeSupport.run(GrailsTestTypeSupport.groovy:121)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runTests(GrailsProjectTestRunner.groovy:415)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.processTests(GrailsProjectTestRunner.groovy:395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1152)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner$_runAllTests_closure7.doCall(GrailsProjectTestRunner.groovy:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:4271)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1408)
	at org.codehaus.groovy.runtime.dgm$151.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy:299)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy:214)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner$runAllTests$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.grails.cli.fork.testing.ForkedGrailsTestRunner.runInstance(ForkedGrailsTestRunner.groovy:128)
	at org.codehaus.groovy.grails.cli.fork.ForkedGrailsProjectClassExecutor.run(ForkedGrailsProjectClassExecutor.groovy:74)
	at org.codehaus.groovy.grails.cli.fork.testing.ForkedGrailsTestRunner.main(ForkedGrailsTestRunner.groovy:75)
2014-12-02 15:23:37,566 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-02 15:23:37,567 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-02 15:23:37,567 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-02 15:23:37,607 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-02 15:23:37,607 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-04 15:46:56,779 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.grails.test.spock.GrailsSpecTestType.doRun(GrailsSpecTestType.groovy:147)
	at org.codehaus.groovy.grails.test.support.GrailsTestTypeSupport.run(GrailsTestTypeSupport.groovy:121)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runTests(GrailsProjectTestRunner.groovy:415)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.processTests(GrailsProjectTestRunner.groovy:395)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1152)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner$_runAllTests_closure7.doCall(GrailsProjectTestRunner.groovy:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:4271)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1408)
	at org.codehaus.groovy.runtime.dgm$151.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy:299)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy:214)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner.runAllTests(GrailsProjectTestRunner.groovy)
	at org.codehaus.groovy.grails.test.runner.GrailsProjectTestRunner$runAllTests$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.grails.cli.fork.testing.ForkedGrailsTestRunner.runInstance(ForkedGrailsTestRunner.groovy:128)
	at org.codehaus.groovy.grails.cli.fork.ForkedGrailsProjectClassExecutor.run(ForkedGrailsProjectClassExecutor.groovy:74)
	at org.codehaus.groovy.grails.cli.fork.testing.ForkedGrailsTestRunner.main(ForkedGrailsTestRunner.groovy:75)
2014-12-04 15:46:56,782 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-04 15:46:56,786 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-04 15:46:56,786 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-04 15:46:56,845 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-04 15:46:56,845 [main] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: No tests found matching grails test target pattern filter from org.junit.runner.Request$1@351e414e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:35)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
2014-12-04 15:57:43,420 [main] ERROR StackTrace  - Full Stack Trace:
Condition not satisfied:

user.errors.getFieldError("password").code == "matches.invalid"
|    |      |                         |    |
|    |      |                         |    false
|    |      |                         |    8 differences (52% similarity)
|    |      |                         |    (v)a(lidator).invalid
|    |      |                         |    (m)a(tches--).invalid
|    |      |                         validator.invalid
|    |      Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
|    grails.validation.ValidationErrors: 1 errors
|    Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
com.rocksoft.User : (unsaved)

	at com.rocksoft.UserIntegrationIntegrationSpec.Saving a user with a login id that matches password causes an error(UserIntegrationIntegrationSpec.groovy:75)
2014-12-04 15:57:43,448 [main] ERROR StackTrace  - Full Stack Trace:
Condition not satisfied:

user.errors.getFieldError("password").code == "matches.invalid"
|    |      |                         |    |
|    |      |                         |    false
|    |      |                         |    8 differences (52% similarity)
|    |      |                         |    (v)a(lidator).invalid
|    |      |                         |    (m)a(tches--).invalid
|    |      |                         validator.invalid
|    |      Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
|    grails.validation.ValidationErrors: 1 errors
|    Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
com.rocksoft.User : (unsaved)

	at com.rocksoft.UserIntegrationIntegrationSpec.Saving a user with a login id that matches password causes an error(UserIntegrationIntegrationSpec.groovy:75)
2014-12-04 15:57:43,450 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Condition not satisfied:

user.errors.getFieldError("password").code == "matches.invalid"
|    |      |                         |    |
|    |      |                         |    false
|    |      |                         |    8 differences (52% similarity)
|    |      |                         |    (v)a(lidator).invalid
|    |      |                         |    (m)a(tches--).invalid
|    |      |                         validator.invalid
|    |      Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
|    grails.validation.ValidationErrors: 1 errors
|    Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
com.rocksoft.User : (unsaved)

	at com.rocksoft.UserIntegrationIntegrationSpec.Saving a user with a login id that matches password causes an error(UserIntegrationIntegrationSpec.groovy:75)
2014-12-04 15:57:43,450 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Condition not satisfied:

user.errors.getFieldError("password").code == "matches.invalid"
|    |      |                         |    |
|    |      |                         |    false
|    |      |                         |    8 differences (52% similarity)
|    |      |                         |    (v)a(lidator).invalid
|    |      |                         |    (m)a(tches--).invalid
|    |      |                         validator.invalid
|    |      Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
|    grails.validation.ValidationErrors: 1 errors
|    Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
com.rocksoft.User : (unsaved)

	at com.rocksoft.UserIntegrationIntegrationSpec.Saving a user with a login id that matches password causes an error(UserIntegrationIntegrationSpec.groovy:75)
2014-12-04 15:57:43,484 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Condition not satisfied:

user.errors.getFieldError("password").code == "matches.invalid"
|    |      |                         |    |
|    |      |                         |    false
|    |      |                         |    8 differences (52% similarity)
|    |      |                         |    (v)a(lidator).invalid
|    |      |                         |    (m)a(tches--).invalid
|    |      |                         validator.invalid
|    |      Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
|    grails.validation.ValidationErrors: 1 errors
|    Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
com.rocksoft.User : (unsaved)

	at com.rocksoft.UserIntegrationIntegrationSpec.Saving a user with a login id that matches password causes an error(UserIntegrationIntegrationSpec.groovy:75)
2014-12-04 15:57:43,484 [main] ERROR StackTrace  - Full Stack Trace:
junit.framework.AssertionFailedError: Condition not satisfied:

user.errors.getFieldError("password").code == "matches.invalid"
|    |      |                         |    |
|    |      |                         |    false
|    |      |                         |    8 differences (52% similarity)
|    |      |                         |    (v)a(lidator).invalid
|    |      |                         |    (m)a(tches--).invalid
|    |      |                         validator.invalid
|    |      Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
|    grails.validation.ValidationErrors: 1 errors
|    Field error in object 'com.rocksoft.User' on field 'password': rejected value [abcdefg]; codes [com.rocksoft.User.password.validator.error.com.rocksoft.User.password,com.rocksoft.User.password.validator.error.password,com.rocksoft.User.password.validator.error.java.lang.String,com.rocksoft.User.password.validator.error,user.password.validator.error.com.rocksoft.User.password,user.password.validator.error.password,user.password.validator.error.java.lang.String,user.password.validator.error,com.rocksoft.User.password.validator.invalid.com.rocksoft.User.password,com.rocksoft.User.password.validator.invalid.password,com.rocksoft.User.password.validator.invalid.java.lang.String,com.rocksoft.User.password.validator.invalid,user.password.validator.invalid.com.rocksoft.User.password,user.password.validator.invalid.password,user.password.validator.invalid.java.lang.String,user.password.validator.invalid,validator.invalid.com.rocksoft.User.password,validator.invalid.password,validator.invalid.java.lang.String,validator.invalid]; arguments [password,class com.rocksoft.User,abcdefg]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]
com.rocksoft.User : (unsaved)

	at com.rocksoft.UserIntegrationIntegrationSpec.Saving a user with a login id that matches password causes an error(UserIntegrationIntegrationSpec.groovy:75)
